<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [22]:
import numpy as np



#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [23]:
lista1 = list(range(0,10))
print(lista1)
array_monodimensional = np.array(lista1)
print(array_monodimensional)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [24]:
array_bidimensional = array_monodimensional.reshape(2,5)
print(array_bidimensional)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [25]:
mi_array = np.array([0, 2, 0, 3, 0, 4, 0])
print(mi_array)
print(np.where(mi_array>0))


[0 2 0 3 0 4 0]
(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [26]:

random_array=np.random.randint(0,2,3)
print(random_array)

[1 0 0]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [27]:
random_array=np.random.randint(1,10,10)
print(random_array)
minimo=np.min(random_array)
maximo = np.max(random_array)
print(minimo, maximo)

[1 6 6 4 1 7 2 8 4 2]
1 8


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [28]:
random_array=np.random.randint(1,10,10)
print(random_array)
array_invertido = np.flip(random_array)
print(array_invertido)

[8 9 1 7 2 5 6 3 3 1]
[1 3 3 6 5 2 7 1 9 8]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [29]:
auxiliar=np.arange(1,25)
array_tridimensional=auxiliar.reshape(2, 3, 4) # Este es el array tridimensional pedido
print(array_tridimensional)
primer_quince=array_tridimensional[1, 0, 2] # Este es el primer 15 que aparece
print("El primer quince es: ", primer_quince)
ultima_fila = array_tridimensional[1 ,2, :] # Ultima fila del ultimo array
print("La ultima fila es: ", ultima_fila)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
El primer quince es:  15
La ultima fila es:  [21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [30]:
array_tridimensional=np.random.randint(1,30,(3,2,5))
print(array_tridimensional)
subarray1 = array_tridimensional[0,:,:2] #primer subarray que nos piden
print("El primer subarray que nos piden es", subarray1)
subarray2 = array_tridimensional[1:,:,:]
print("El segundo subarray que nos piden es", subarray2)

[[[16 14 25 19 20]
  [ 5 21  4 16 17]]

 [[16 17  9  5 24]
  [15 15 16 13 14]]

 [[10 18 19 25 21]
  [24 14  2 21 19]]]
El primer subarray que nos piden es [[16 14]
 [ 5 21]]
El segundo subarray que nos piden es [[[16 17  9  5 24]
  [15 15 16 13 14]]

 [[10 18 19 25 21]
  [24 14  2 21 19]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [31]:
auxiliar=np.arange(1,25)
array_tridimensional=auxiliar.reshape(4, 3, 2)
array_tridimensional[1, 1, :] = 0 # Cambiamos todos los elementos de la segunda fila del segundo array por 0
print(array_tridimensional)
array_tridimensional[-1, :, :] = -1 # Cambiamos todos los valores del último array a -1
print(array_tridimensional)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [32]:
# Generamos el array del enunciado
array_tridimensional = np.arange(-10, 14).reshape((2, 4, 3))
print(array_tridimensional)
# Elementos mayores a 5
mayores_que_5 = array_tridimensional[array_tridimensional > 5]
print(mayores_que_5)

# Reemplazar todos los elementos negativos por 0
array_tridimensional[array_tridimensional < 0] = 0

print(array_tridimensional)

[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]
[ 6  7  8  9 10 11 12 13]
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  1]]

 [[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]
  [11 12 13]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [33]:
# Generamos el array del enunciado
array_tridimensional = np.arange(1, 28).reshape((3, 3, 3))

# Primer subarray pedido
subarray1 = array_tridimensional[1, :, :2]
print(subarray1)

# Segundo subarray pedido
subarray2 = array_tridimensional[2][array_tridimensional[2] > 20]
print(subarray2)



[[10 11]
 [13 14]
 [16 17]]
[21 22 23 24 25 26 27]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [34]:
array_random = np.random.randint(1,1000,10)
print(array_random)
#Reemplazamos el maximo y el minimo por 0
max_index = np.argmax(array_random) 
min_index = np.argmin(array_random)
array_random[max_index] = 0
array_random[min_index] = 0
print(array_random)

[554 968 511 414 324 355 312 434 659 283]
[554   0 511 414 324 355 312 434 659   0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [35]:
array_random = np.random.randint(1,1000,15)
print(array_random)
array_random_ordenado = np.sort(array_random)
print("La lista reordenada en orden ascendente es:")
print(array_random_ordenado)

[937 635 970 213 993 128 675 770 425 218 481 808  24  58 617]
La lista reordenada en orden ascendente es:
[ 24  58 128 213 218 425 481 617 635 675 770 808 937 970 993]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [36]:
matriz = np.random.randint(1,10,[4, 4])
print(matriz)
suma_elementos=sum(sum(matriz[:,:])) #Aqui hacemos primero la suma de cada columna y luego la suma de esas sumas
print(suma_elementos)


[[1 5 4 4]
 [5 9 3 1]
 [6 2 5 7]
 [1 8 4 5]]
70


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [37]:
matriz=np.zeros([5,5])
print(matriz)
matriz [0,:]=1
matriz [4,:]=1
matriz [:,0]=1
matriz [:,4]=1
matriz

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [38]:
array_random = np.random.randint(1,10,10)
print(array_random)
media=np.mean(array_random)
print("La media es: ", media)

[2 6 2 5 1 3 9 2 8 1]
La media es:  3.9


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [39]:
array_tridimensional = np.arange(1, 25).reshape((2, 3, 4))
print(array_tridimensional)
array_transpuesto = np.transpose(array_tridimensional, (2, 1, 0))
print(array_transpuesto)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


 El parámetro (1, 0, 2) indica que el segundo eje original (índice 1) se convierte en el primer eje, el primer eje original (índice 0) se convierte en el segundo eje, y el tercer eje (índice 2) permanece igual. Las variables cambian segun ese giro de los ejes

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [41]:

array_original = np.arange(1, 25).reshape((2, 3, 4))
array_transpuesto = np.transpose(array_original, (2, 1, 0))
print(array_transpuesto)

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [ ]:
array_original = np.arange(1, 25).reshape((3, 2, 4))
print("Array original (3, 2, 4):")
print(array_original)
print("Forma del array original:", array_original.shape)

    

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.