<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [1]:
import numpy as np



#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [2]:
lista1 = list(range(0,10))
print(lista1)
array_monodimensional = np.array(lista1)
print(array_monodimensional)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [3]:
array_bidimensional = array_monodimensional.reshape(2,5)
print(array_bidimensional)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [4]:
mi_array = np.array([0, 2, 0, 3, 0, 4, 0])
print(mi_array)
print(np.where(mi_array>0))


[0 2 0 3 0 4 0]
(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [5]:

random_array=np.random.randint(0,2,3)
print(random_array)

[1 0 0]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [6]:
random_array=np.random.randint(1,10,10)
print(random_array)
minimo=np.min(random_array)
maximo = np.max(random_array)
print(minimo, maximo)

[1 8 5 2 9 3 6 4 5 4]
1 9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [7]:
random_array=np.random.randint(1,10,10)
print(random_array)
array_invertido = np.flip(random_array)
print(array_invertido)

[8 4 2 3 1 4 6 1 9 3]
[3 9 1 6 4 1 3 2 4 8]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [8]:
auxiliar=np.arange(1,25)
array_tridimensional=auxiliar.reshape(2, 3, 4) # Este es el array tridimensional pedido
print(array_tridimensional)
primer_quince=array_tridimensional[1, 0, 2] # Este es el primer 15 que aparece
print("El primer quince es: ", primer_quince)
ultima_fila = array_tridimensional[1 ,2, :] # Ultima fila del ultimo array
print("La ultima fila es: ", ultima_fila)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
El primer quince es:  15
La ultima fila es:  [21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [9]:
array_tridimensional=np.random.randint(1,30,(3,2,5))
print(array_tridimensional)
subarray1 = array_tridimensional[0,:,:2] #primer subarray que nos piden
print("El primer subarray que nos piden es", subarray1)
subarray2 = array_tridimensional[1:,:,:]
print("El segundo subarray que nos piden es", subarray2)

[[[ 5 16 19 16  1]
  [13 16 16 19 29]]

 [[ 8  8  1 17  9]
  [24 11  7 11  1]]

 [[ 4 29 19  8 18]
  [ 7 14  7 28 26]]]
El primer subarray que nos piden es [[ 5 16]
 [13 16]]
El segundo subarray que nos piden es [[[ 8  8  1 17  9]
  [24 11  7 11  1]]

 [[ 4 29 19  8 18]
  [ 7 14  7 28 26]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [10]:
auxiliar=np.arange(1,25)
array_tridimensional=auxiliar.reshape(4, 3, 2)
array_tridimensional[1, 1, :] = 0 # Cambiamos todos los elementos de la segunda fila del segundo array por 0
print(array_tridimensional)
array_tridimensional[-1, :, :] = -1 # Cambiamos todos los valores del último array a -1
print(array_tridimensional)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [11]:
# Generamos el array del enunciado
array_tridimensional = np.arange(-10, 14).reshape((2, 4, 3))
print(array_tridimensional)
# Elementos mayores a 5
mayores_que_5 = array_tridimensional[array_tridimensional > 5]
print(mayores_que_5)

# Reemplazar todos los elementos negativos por 0
array_tridimensional[array_tridimensional < 0] = 0

print(array_tridimensional)

[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]
[ 6  7  8  9 10 11 12 13]
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  1]]

 [[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]
  [11 12 13]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [12]:
# Generamos el array del enunciado
array_tridimensional = np.arange(1, 28).reshape((3, 3, 3))

# Primer subarray pedido
subarray1 = array_tridimensional[1, :, :2]
print(subarray1)

# Segundo subarray pedido
subarray2 = array_tridimensional[2][array_tridimensional[2] > 20]
print(subarray2)



[[10 11]
 [13 14]
 [16 17]]
[21 22 23 24 25 26 27]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [13]:
array_random = np.random.randint(1,1000,10)
print(array_random)
#Reemplazamos el maximo y el minimo por 0
max_index = np.argmax(array_random) 
min_index = np.argmin(array_random)
array_random[max_index] = 0
array_random[min_index] = 0
print(array_random)

[995 320 100 615  24 954 499 242 312 892]
[  0 320 100 615   0 954 499 242 312 892]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [14]:
array_random = np.random.randint(1,1000,15)
print(array_random)
array_random_ordenado = np.sort(array_random)
print("La lista reordenada en orden ascendente es:")
print(array_random_ordenado)

[624 461 257 885 437 821 300 491 415 439 301 161 522 335 761]
La lista reordenada en orden ascendente es:
[161 257 300 301 335 415 437 439 461 491 522 624 761 821 885]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [15]:
matriz = np.random.randint(1,10,[4, 4])
print(matriz)
suma_elementos=sum(sum(matriz[:,:])) #Aqui hacemos primero la suma de cada columna y luego la suma de esas sumas
print(suma_elementos)


[[4 6 4 7]
 [1 8 6 8]
 [3 4 3 2]
 [8 5 9 7]]
85


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [16]:
matriz=np.zeros([5,5])
print(matriz)
matriz [0,:]=1
matriz [4,:]=1
matriz [:,0]=1
matriz [:,4]=1
matriz

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [17]:
array_random = np.random.randint(1,10,10)
print(array_random)
media=np.mean(array_random)
print("La media es: ", media)

[5 1 4 7 9 8 4 8 7 7]
La media es:  6.0


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [18]:
array_tridimensional = np.arange(1, 25).reshape((2, 3, 4))
print(array_tridimensional)
array_transpuesto = np.transpose(array_tridimensional, (2, 1, 0))
print(array_transpuesto)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


 El parámetro (1, 0, 2) indica que el segundo eje original (índice 1) se convierte en el primer eje, el primer eje original (índice 0) se convierte en el segundo eje, y el tercer eje (índice 2) permanece igual. Las variables cambian segun ese giro de los ejes

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [19]:

array_tridimensional = np.arange(1, 25).reshape((2, 3, 4))
array_transpuesto = np.transpose(array_tridimensional, (2, 1, 0))
print(array_transpuesto)

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [20]:
array_tridimensional = np.arange(1, 25).reshape((3, 2, 4))
print("Array 1 (3, 2, 4):")
print(array_tridimensional)


    

Array 1 (3, 2, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [21]:
array_1 = np.random.randint(-10, 11, size=(3, 4, 5))


print(array_1)

#Calculamos mediana, máximo, mínimo
mediana = np.median(array_1)
maximo = np.max(array_1)
minimo = np.min(array_1)

# Creamos un array vacío de la misma forma con dtype=object para almacenar cadenas de texto
array_reemplazado = np.empty_like(array_1, dtype=object)

# Aplicamos las condiciones con np.where:

array_reemplazado = np.where(array_1 == maximo, "MAX", array_reemplazado)
array_reemplazado = np.where(array_1 == minimo, "MIN", array_reemplazado)
array_reemplazado = np.where(array_1 == mediana, "M", array_reemplazado)
array_reemplazado = np.where((array_1 > mediana) & (array_1 != maximo), "X", array_reemplazado)
array_reemplazado = np.where((array_1 < mediana) & (array_1 != minimo), "Y", array_reemplazado)

print("Array Reemplazado (3, 4, 5):")
print(array_reemplazado)


[[[ -3  -8   1   4   9]
  [  7   7   4  -5   6]
  [  3   5  10   7   5]
  [  3   3   4   0   8]]

 [[ -1  -1   3  -7   7]
  [  7   7   7  -6 -10]
  [ -9   7   4   9   8]
  [ -3   0  -9   2  -7]]

 [[ -8   8   6  -6  10]
  [ -3  -7  -5   8   7]
  [ -2   7  -5   6   1]
  [  9  -8   3  -5 -10]]]
Array Reemplazado (3, 4, 5):
[[['Y' 'Y' 'Y' 'X' 'X']
  ['X' 'X' 'X' 'Y' 'X']
  ['M' 'X' 'MAX' 'X' 'X']
  ['M' 'M' 'X' 'Y' 'X']]

 [['Y' 'Y' 'M' 'Y' 'X']
  ['X' 'X' 'X' 'Y' 'MIN']
  ['Y' 'X' 'X' 'X' 'X']
  ['Y' 'Y' 'Y' 'Y' 'Y']]

 [['Y' 'X' 'X' 'Y' 'MAX']
  ['Y' 'Y' 'Y' 'X' 'X']
  ['Y' 'X' 'Y' 'X' 'Y']
  ['X' 'Y' 'M' 'Y' 'MIN']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [32]:
matriz = np.random.randint(1,10,[4, 4])

# Imprimimos la matriz respetando las restricciones que nos pone el enunciado

for fila in matriz:
    print(fila)

# Función para comparar fila con columna
def comparar_f_c(matriz):
    filas = len(matriz)
    columnas = len(matriz[0])

    # Se recorren todas las filas
    for i in range(filas):
        # y todas las columnas
        for j in range(columnas):
            # Comprobamos si todos los elementos de la fila i son iguales a los de la columna j
            son_iguales = True
            for k in range(filas):
                if matriz[i][k] != matriz[k][j]:
                    son_iguales = False
                    break
            
            if son_iguales:
                print(f"La fila {i + 1} es igual a la columna {j + 1}")
                return True
    
    print("No hay filas que sean iguales a alguna columna.")
    return False

# Llamamos a la función para comparar filas y columnas
comparar_f_c(matriz)


[9 8 6 7]
[4 3 4 7]
[9 3 2 8]
[5 3 2 6]
No hay filas que sean iguales a alguna columna.


False